stages:
  materialize:
    do:
      cmd: python3 ../../../util/run_stage.py --backend "${item.backend}" --country
        "${item.country}" --wave "${item.wave}" --table "${item.table}" --format "${item.format}"
        --target "${item.target}"
      deps:
      - ../../../cli.py
      - ../../../country.py
      - ../../../local_tools.py
      - _
      outs:
      - var/${item.table}.${item.format}
    foreach:
      uganda::2018_19::cluster_features:
        country: Uganda
        wave: 2018-19
        table: cluster_features
        format: parquet
        backend: cli
        target: ''
      uganda::2018_19::people_last7days:
        country: Uganda
        wave: 2018-19
        table: people_last7days
        format: parquet
        backend: cli
        target: ''
