"""Aggregate per-country JSON probes into a single rescan audit (Markdown)."""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
PER = HERE / "per_country"
OUT = HERE / "rescan_2026-04-13.md"


def fmt_int(n) -> str:
    if n is None:
        return "—"
    try:
        return f"{int(n):,}"
    except Exception:
        return str(n)


def main():
    files = sorted(PER.glob("*.json"))
    recs = [json.loads(p.read_text()) for p in files]
    by_status: dict[str, list[dict]] = {}
    for r in recs:
        by_status.setdefault(r.get("status", "unknown"), []).append(r)

    lines: list[str] = []
    lines.append("# household_roster — Rescan Audit\n")
    lines.append("**Date**: 2026-04-13 (auto-generated by `slurm_logs/roster_scan_2026-04-13/aggregate.py`)\n")
    lines.append(f"**Data source**: `Country(name).household_roster()` via the API (kinship expansion + canonical spellings applied), {len(recs)} countries probed.\n")

    # -----------------------------------------------------------------
    # 1. Summary table
    # -----------------------------------------------------------------
    lines.append("## 1. Per-Country Status\n")
    lines.append("| Country | Status | Rows | Sex non-canonical | Age dtype | Age neg | Age >120 | Age non-num | Relationship unknowns |")
    lines.append("|---------|--------|-----:|:------------------|:----------|--------:|---------:|------------:|-----------------------:|")
    for r in sorted(recs, key=lambda x: x["country"]):
        status = r.get("status", "?")
        rows = fmt_int(r.get("rows"))
        if status != "ok":
            lines.append(f"| {r['country']} | **{status}** | — | — | — | — | — | — | — |")
            continue
        sex = r.get("sex", {}) or {}
        nc = sex.get("non_canonical") or []
        nc_label = ", ".join(f"`{v}`" for v in nc) if nc else "—"
        age = r.get("age", {}) or {}
        rel = r.get("relationship", {}) or {}
        unk = rel.get("unknown_labels") or []
        unk_count = len(unk)
        lines.append(
            f"| {r['country']} | ok | {rows} | {nc_label} | "
            f"{age.get('dtype','—')} | {age.get('n_negative',0)} | "
            f"{age.get('n_gt_120',0)} | {age.get('n_non_numeric',0)} | "
            f"{unk_count} |"
        )
    lines.append("")

    # -----------------------------------------------------------------
    # 2. Countries that errored
    # -----------------------------------------------------------------
    errs = by_status.get("error", []) + by_status.get("worker_error", [])
    if errs:
        lines.append("## 2. Errored Countries\n")
        for r in errs:
            lines.append(f"### {r['country']}\n")
            lines.append(f"- Elapsed: {r.get('elapsed_s','—')}s")
            lines.append(f"- Error: `{r.get('error','')}`")
            tb = (r.get("traceback") or "").strip()
            if tb:
                lines.append(f"\n```\n{tb[-1500:]}\n```\n")
        lines.append("")

    # -----------------------------------------------------------------
    # 3. Sex findings
    # -----------------------------------------------------------------
    lines.append("## 3. Sex Canonicalization\n")
    sex_offenders = []
    for r in recs:
        if r.get("status") != "ok":
            continue
        sex = r.get("sex", {}) or {}
        if sex.get("non_canonical"):
            sex_offenders.append(r)
    if not sex_offenders:
        lines.append("All built countries pass {M, F}.\n")
    else:
        lines.append(f"{len(sex_offenders)} country/ies produce non-canonical Sex values (expected: {{M, F}} + NA only).\n")
        for r in sex_offenders:
            sex = r["sex"]
            lines.append(f"### {r['country']}")
            lines.append(f"- Unique values: `{sex.get('unique')}`")
            lines.append(f"- Non-canonical counts: `{sex.get('non_canonical_counts')}`")
            lines.append(f"- Non-null / null: {fmt_int(sex.get('n_non_null'))} / {fmt_int(sex.get('n_null'))}\n")

    # -----------------------------------------------------------------
    # 4. Age findings
    # -----------------------------------------------------------------
    lines.append("## 4. Age Quality\n")
    age_bad = []
    for r in recs:
        if r.get("status") != "ok":
            continue
        age = r.get("age", {}) or {}
        if (age.get("n_negative", 0) or age.get("n_gt_120", 0)
            or age.get("n_non_numeric", 0)):
            age_bad.append(r)
    if not age_bad:
        lines.append("All built countries have clean Age values.\n")
    else:
        lines.append(f"{len(age_bad)} country/ies have negative, >120, or non-numeric Age.\n")
        lines.append("| Country | dtype | neg | >120 | non-numeric | min | max | non-num samples |")
        lines.append("|---------|-------|----:|-----:|------------:|----:|----:|-----------------|")
        for r in age_bad:
            age = r["age"]
            samples = age.get("non_numeric_samples") or {}
            samples_str = ", ".join(f"`{k}`×{v}" for k, v in list(samples.items())[:3]) or "—"
            lines.append(
                f"| {r['country']} | {age.get('dtype','—')} | "
                f"{age.get('n_negative',0)} | {age.get('n_gt_120',0)} | "
                f"{age.get('n_non_numeric',0)} | "
                f"{age.get('min','—')} | {age.get('max','—')} | {samples_str} |"
            )
        lines.append("")

    # -----------------------------------------------------------------
    # 5. Relationship coverage
    # -----------------------------------------------------------------
    lines.append("## 5. Relationship Labels Not in kinship.yml\n")
    unk_per_country = []
    all_unknown: dict[str, list[str]] = {}
    for r in recs:
        if r.get("status") != "ok":
            continue
        rel = r.get("relationship", {}) or {}
        unk = rel.get("unknown_labels") or []
        if unk:
            unk_per_country.append(r)
            for label in unk:
                all_unknown.setdefault(label, []).append(r["country"])
    if not unk_per_country:
        lines.append("All Relationship labels in kinship.yml.\n")
    else:
        lines.append(f"{len(unk_per_country)} country/ies produce Relationship labels not present (even after title-case) in `kinship.yml`.\n")
        for r in unk_per_country:
            rel = r["relationship"]
            lines.append(f"### {r['country']}")
            lines.append(f"- {len(rel.get('unknown_labels', []))} unknown labels out of {rel.get('n_unique')} unique")
            top = rel.get("unknown_label_counts") or {}
            if top:
                lines.append("- Top unknowns by row count:")
                for k, v in top.items():
                    lines.append(f"  - `{k}` → {fmt_int(v)}")
            lines.append("")

        # Cross-country view: labels shared across countries
        shared = {k: v for k, v in all_unknown.items() if len(v) > 1}
        if shared:
            lines.append("### Cross-country shared unknowns (add these to `kinship.yml` first)\n")
            for label, countries in sorted(shared.items(), key=lambda kv: -len(kv[1])):
                lines.append(f"- `{label}` — {len(countries)} countries: {', '.join(countries)}")
            lines.append("")

    # -----------------------------------------------------------------
    # 6. Kinship derived columns coverage
    # -----------------------------------------------------------------
    lines.append("## 6. Kinship Derived Columns (`Generation`, `Distance`, `Affinity`)\n")
    missing_derived = []
    high_null_affinity = []
    for r in recs:
        if r.get("status") != "ok":
            continue
        kd = r.get("kinship_derived", {}) or {}
        if not (kd.get("Generation_present") and kd.get("Distance_present") and kd.get("Affinity_present")):
            missing_derived.append(r)
        else:
            null_rate = kd.get("Affinity_null_rate") or 0
            if null_rate > 0.05:
                high_null_affinity.append((r, null_rate))
    if missing_derived:
        lines.append("Countries missing derived columns (should not happen if `_finalize_result` fires):")
        for r in missing_derived:
            lines.append(f"- {r['country']} — kd={r.get('kinship_derived')}")
        lines.append("")
    else:
        lines.append("All built countries have Generation / Distance / Affinity columns.\n")
    if high_null_affinity:
        lines.append("### Countries with Affinity null rate > 5% (unknown Relationship labels)\n")
        lines.append("| Country | Affinity null rate |")
        lines.append("|---------|-------------------:|")
        for r, rate in sorted(high_null_affinity, key=lambda x: -x[1]):
            lines.append(f"| {r['country']} | {rate:.1%} |")
        lines.append("")

    # -----------------------------------------------------------------
    # 7. Extra / rogue columns
    # -----------------------------------------------------------------
    lines.append("## 7. Extra Columns (beyond canonical)\n")
    extras_by_country: dict[str, list[str]] = {}
    all_extras: dict[str, list[str]] = {}
    for r in recs:
        if r.get("status") != "ok":
            continue
        xs = r.get("extra_columns") or []
        if xs:
            extras_by_country[r["country"]] = xs
            for x in xs:
                all_extras.setdefault(x, []).append(r["country"])
    if not extras_by_country:
        lines.append("No extra columns across built countries.\n")
    else:
        lines.append("| Column | Countries |")
        lines.append("|--------|-----------|")
        for col, countries in sorted(all_extras.items(), key=lambda kv: (-len(kv[1]), kv[0])):
            lines.append(f"| `{col}` | {', '.join(countries)} |")
        lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
