stages:
  materialize:
    foreach:
      malawi::2019_20::household_roster:
        country: Malawi
        wave: 2019-20
        table: household_roster
        format: parquet
      malawi::2019_20::food_acquired:
        country: Malawi
        wave: 2019-20
        table: food_acquired
        format: parquet
    do:
      cmd: python3 -m lsms_library.cli materialize --country ${item.country} --wave ${item.wave} --table ${item.table} --format ${item.format} --out build/${item.wave}/${item.table}.${item.format}
      deps:
      - ../../cli.py
      - ../../country.py
      - ../../local_tools.py
      - _
      - ${item.wave}/_
      outs:
      - build/${item.wave}/${item.table}.${item.format}
