stages:
  materialize:
    do:
      cmd: cd _ && LSMS_USE_DVC_CACHE=false python3 -m lsms_library.cli materialize
        --country "${item.country}" --wave "${item.wave}" --table "${item.table}"
        --format "${item.format}" --out ../var/${item.table}.${item.format}
      deps:
      - ../../../cli.py
      - ../../../country.py
      - ../../../local_tools.py
      - _
      outs:
      - var/${item.table}.${item.format}
    foreach:
      uganda::2009_10::cluster_features:
        country: Uganda
        wave: 2009-10
        table: cluster_features
        format: parquet
      uganda::2009_10::household_roster:
        country: Uganda
        wave: 2009-10
        table: household_roster
        format: parquet
      uganda::2009_10::people_last7days:
        country: Uganda
        wave: 2009-10
        table: people_last7days
        format: parquet
