stages:
  materialize:
    foreach:
      malawi::2013_14::cluster_features:
        country: Malawi
        wave: 2013-14
        table: cluster_features
        format: parquet
      malawi::2013_14::household_roster:
        country: Malawi
        wave: 2013-14
        table: household_roster
        format: parquet
      malawi::2013_14::interview_date:
        country: Malawi
        wave: 2013-14
        table: interview_date
        format: parquet
      malawi::2013_14::subjective_well_being:
        country: Malawi
        wave: 2013-14
        table: subjective_well_being
        format: parquet
      malawi::2013_14::panel_ids:
        country: Malawi
        wave: 2013-14
        table: panel_ids
        format: parquet
      malawi::2013_14::food_acquired:
        country: Malawi
        wave: 2013-14
        table: food_acquired
        format: parquet
      malawi::2013_14::food_expenditures:
        country: Malawi
        wave: 2013-14
        table: food_expenditures
        format: parquet
      malawi::2013_14::household_characteristics:
        country: Malawi
        wave: 2013-14
        table: household_characteristics
        format: parquet
      malawi::2013_14::food_prices:
        country: Malawi
        wave: 2013-14
        table: food_prices
        format: parquet
    do:
      cmd: python3 -m lsms_library.cli materialize --country {item.country} --wave
        ${item.wave} --table ${item.table} --format ${item.format} --out _/${item.table}.${item.format}
      deps:
      - ../../../cli.py
      - ../../../country.py
      - ../../../local_tools.py
      - _
      outs:
      - _/${item.table}.${item.format}
