stages:
  materialize:
    do:
      cmd: cd _ && LSMS_USE_DVC_CACHE=false python3 -m lsms_library.cli materialize
        --country "${item.country}" --wave "${item.wave}" --table "${item.table}"
        --format "${item.format}" --out ../var/${item.table}.${item.format}
      deps:
      - ../../../cli.py
      - ../../../country.py
      - ../../../local_tools.py
      - _
      outs:
      - var/${item.table}.${item.format}
    foreach:
      uganda::2010_11::cluster_features:
        country: Uganda
        wave: 2010-11
        table: cluster_features
        format: parquet
