stages:
  materialize:
    do:
      cmd: python3 ../../../util/run_stage.py --backend "${item.backend}" --country
        "${item.country}" --wave "${item.wave}" --table "${item.table}" --format "${item.format}"
        --target "${item.target}"
      deps:
      - ../../../cli.py
      - ../../../country.py
      - ../../../local_tools.py
      - ../../../util/run_stage.py
      - _
      outs:
      - ${item.output}
    foreach:
      uganda::2015_16::cluster_features:
        country: Uganda
        wave: 2015-16
        table: cluster_features
        format: parquet
        backend: cli
        target: ''
        output: var/cluster_features.parquet
