#!/usr/bin/env python
"""Generate ``docs/guide/data-methods.md`` from the runtime docstrings.

Why generated and not written
-----------------------------
``Country.food_prices`` and every other data method is synthesised in
``Country.__getattr__`` from ``data_scheme``.  mkdocstrings documents modules
by importing and introspecting them, so a method that does not exist until
attribute-access time is invisible to it: the docs site has pages for
``Country``'s *introspection* helpers and none for the methods users actually
call.

The docstrings themselves are good -- ``help(Country('X').food_prices)``
already explains ``units=``, ``currency=``, ``numeraire=`` and the rest.  The
gap is transport, not content.  So this script asks the library for those
docstrings and writes them to a page, which keeps one source of truth: edit
``doc_parts`` in ``country.py`` and the page follows.  A hand-written guide
would be a second copy, free to drift from the code silently -- the failure
this whole exercise exists to stop.

Run via ``make docs-gen``; ``tests/test_api_discoverability.py`` fails if the
committed page is stale.
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "docs" / "guide" / "data-methods.md"

#: Representative methods, chosen so that between them every kwarg appears.
#: ``age_cuts`` is roster-only and ``basis`` is food_expenditures-only, so a
#: single method can never document the whole surface.
SPECIMENS = [
    ("GhanaLSS", "food_prices", "units, volume_as_mass, currency, numeraire"),
    ("GhanaLSS", "food_expenditures", "basis, valuation"),
    ("GhanaLSS", "household_characteristics", "age_cuts"),
    ("GhanaLSS", "household_roster", "the common kwargs alone"),
]

HEADER = """# Data methods and their keyword arguments

!!! info "This page is generated"
    Generated by `scripts/gen_data_method_docs.py` from the **live docstrings**
    of the generated data methods. Do not edit by hand -- change `doc_parts` in
    `lsms_library/country.py` and re-run `make docs-gen`.

Every table a country declares becomes a method on `Country`:

```python
import lsms_library as ll
gh = ll.Country('GhanaLSS')
gh.food_acquired()          # a declared table
gh.food_prices()            # derived at API time from food_acquired
```

These methods are **created at attribute-access time** from the country's
`data_scheme`, so they have no source definition for the API reference to pick
up -- which is why they are documented here instead of under
[API / Country](../api/country.md).

They share one keyword-argument surface. Not every method accepts every
kwarg: passing one where it does not apply raises `TypeError` naming the
methods that do accept it, rather than being silently ignored.

| kwarg | applies to | what it does |
|---|---|---|
| `waves=` | all | subset of waves; defaults to all available |
| `market=` | all | add a `cluster_features` column (e.g. `'Region'`) as an `m` index level |
| `labels=` | tables with a mapped level | relabel `j` (scalar form) or any level (dict form) |
| `units=` | `food_prices`, `food_quantities` | price/quantity basis -- see below |
| `volume_as_mass=` | `food_prices`, `food_quantities` | treat litres as kg |
| `currency=` | monetary tables | attach the ISO 4217 code as `'index'` or `'column'` |
| `numeraire=` | monetary tables | convert monetary columns to a common numeraire |
| `basis=` | `food_expenditures` | `'purchased'` or `'total'` |
| `valuation=` | `food_expenditures` (with `basis='total'`) | value produced / in-kind rows: `'own_price'`, `'median_price'`, or a tuple applied in order; off by default |
| `age_cuts=` | `household_characteristics` | age-bracket boundaries |

`currency=` and `numeraire=` are mutually exclusive. Available numeraires come
from `lsms_library.conversion.conversion_targets()`:

```
FX, LCU-real-2017, PPP-2011, PPP-2017, PPP-2021, USD-real-2017
```

"""

FOOTER = """
## Discovering this at the console

The same text is on every generated method, so the authoritative copy is always
one call away and can never be staler than the code:

```python
help(ll.Country('GhanaLSS').food_prices)
```
"""


def main() -> int:
    sys.path.insert(0, str(REPO))
    import lsms_library as ll

    parts = [HEADER]
    for country, method, why in SPECIMENS:
        try:
            doc = getattr(ll.Country(country), method).__doc__ or "(no docstring)"
        except Exception as exc:  # pragma: no cover - config-dependent
            print(f"WARNING: {country}.{method} unavailable: {exc}", file=sys.stderr)
            continue
        parts.append(f"\n## `{method}()`\n\nDocuments: {why}.\n\n```\n{doc.rstrip()}\n```\n")
    parts.append(FOOTER)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(parts))
    print(f"wrote {OUT.relative_to(REPO)} ({OUT.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
