#!/usr/bin/env python
"""Promote `.coder/coverage/food_recall.csv` into per-country `_/recall.yml`.

The CSV is the *evidence base* -- one row per `(country, wave)` food cell, with
the window, the ask count, the evidence rung and the citation.  It lives under
`.coder/`, which resolves via `_repo_root()` and therefore exists only in a
source checkout.  The library must not read it: an installed wheel has no
`.coder/`, and `attrs['recall']` has to work there too.

So this script writes the packaged form -- `countries/{C}/_/recall.yml`, a
sibling of `population.yml`, read through `countries_root()`.  Same division of
labour as `promote_population_records.py`: edit the evidence, re-run this, never
hand-edit the generated YAML.

Refuses to write when the CSV contradicts itself, because a generated file that
launders a bad row is worse than no generated file:

  * a rung outside the ladder;
  * a cell with `within_wave_variation` that also carries a single number;
  * `basis: not-recorded` that nonetheless asserts a window;
  * a non-numeric ask count on a cell with no variation axis to explain it.

Usage:  python scripts/promote_recall_records.py [--check]
        --check  validates and reports without writing (for CI / a test).
"""
from __future__ import annotations

import argparse
import csv
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CSV = REPO / ".coder" / "coverage" / "food_recall.csv"
COUNTRIES = REPO / "lsms_library" / "countries"

sys.path.insert(0, str(REPO))
from lsms_library.recall import (  # noqa: E402
    ASK_COUNT_BASES, BASIS_LADDER, VARIATION_AXES,
)

HEADER = """\
# Recall record -- what reference period this survey's food numbers cover.
# One entry per wave, keyed by the API wave label (the value in the `t` level).
#
# GENERATED by scripts/promote_recall_records.py from
# .coder/coverage/food_recall.csv.  Edit the CSV and re-run; do not hand-edit.
#
#   `basis` IS THE EVIDENCE RUNG, AND IT IS NOT DECORATION.
#
# Only 8 of the corpus's 34 stated windows are questionnaire-grade.  A
# `config-comment` rung means a maintainer asserted the number, not that an
# instrument states it -- consumers are entitled to discount it, and a
# `not-recorded` rung means nobody has looked, which is NOT the same as "no
# window exists".  See lsms_library/recall.py and .coder/coverage/food_recall.org.
#
# `n_asks` counts ASKS, not interviewer visits: GLSS7 fields seven visits and
# asks food at six of them, so the exposure is 6 x 5 = 30 days, not 7 x 5 = 35.
#
# A wave whose window varies INSIDE the wave carries `within_wave_variation`
# and leaves the numbers null.  Filling one would be the error the axis flags.

Recall:
"""


def _clean(v: str | None) -> str:
    return (v or "").strip()


def _num(v: str, cast):
    v = _clean(v)
    if not v:
        return None
    try:
        return cast(v)
    except ValueError:
        return None


def validate(rows: list[dict]) -> list[str]:
    """Every reason this CSV may not be promoted."""
    errs: list[str] = []
    for r in rows:
        cell = f"{r['country']} {r['wave']}"
        basis = _clean(r.get("basis")) or "not-recorded"
        var = _clean(r.get("within_wave_variation")) or None
        days = _num(r.get("recall_days", ""), float)
        asks_raw = _clean(r.get("n_visits"))
        asks = _num(asks_raw, int)

        if basis not in BASIS_LADDER:
            errs.append(f"{cell}: basis {basis!r} not in {BASIS_LADDER}")
        if var and var not in VARIATION_AXES:
            errs.append(f"{cell}: within_wave_variation {var!r} not in {VARIATION_AXES}")
        if var and days is not None:
            errs.append(f"{cell}: varies by {var!r} yet carries recall_days={days}")
        if basis == "not-recorded" and days is not None:
            errs.append(f"{cell}: basis='not-recorded' yet asserts recall_days={days}")
        if asks_raw and asks is None and not var:
            errs.append(
                f"{cell}: n_visits={asks_raw!r} is not an integer and no "
                f"within_wave_variation explains why")
    return errs


def ask_count_basis(country: str, record_has_visit_level: bool, asks) -> str:
    """`measured` where the delivered table can show the count; else `declared`.

    This is @ligon's requirement made a field: where the survey published
    per-ask structure the count is observable in the data; where it did not --
    most of the corpus -- we are relying on what the manual claims, and the
    consumer should be able to see which they have.
    """
    if asks is None:
        return "unknown"
    if record_has_visit_level and asks > 1:
        return "measured"
    return "declared"


def render(country: str, rows: list[dict], has_visit: bool) -> str:
    out = [HEADER]
    for r in sorted(rows, key=lambda x: x["wave"]):
        wave = r["wave"]
        var = _clean(r.get("within_wave_variation")) or None
        days = _num(r.get("recall_days", ""), float)
        asks = _num(_clean(r.get("n_visits")), int)
        # A varying cell carries the axis, never a number.
        if var:
            days, asks = None, None
        basis = _clean(r.get("basis")) or "not-recorded"
        acb = ask_count_basis(country, has_visit, asks)

        out.append(f"  '{wave}':\n")
        out.append(f"    basis: {basis}\n")
        out.append(f"    ask_count_basis: {acb}\n")
        if days is not None:
            out.append(f"    recall_days: {days:g}\n")
        if asks is not None:
            out.append(f"    n_asks: {asks}\n")
        if var:
            out.append(f"    within_wave_variation: {var}\n")
        for key, src in (("recall_verbatim", "recall_verbatim"),
                         ("evidence", "evidence"), ("notes", "notes")):
            val = _clean(r.get(src))
            if val:
                out.append(f"    {key}: {_scalar(val)}\n")
        n_items = _num(_clean(r.get("n_items_delivered")), int)
        if n_items is not None:
            out.append(f"    n_items_delivered: {n_items}\n")
    return "".join(out)


def _scalar(v: str) -> str:
    """Quote so a colon or a leading digit cannot re-parse as structure."""
    return "'" + v.replace("'", "''") + "'"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="validate and report; write nothing")
    args = ap.parse_args()

    rows = list(csv.DictReader(CSV.open()))
    errs = validate(rows)
    if errs:
        print(f"REFUSING to promote -- {len(errs)} contradiction(s) in {CSV}:")
        for e in errs:
            print("  " + e)
        return 1

    by_country: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_country[r["country"]].append(r)

    written = 0
    for country, crows in sorted(by_country.items()):
        cdir = COUNTRIES / country / "_"
        if not cdir.is_dir():
            print(f"  skip {country}: no {cdir}")
            continue
        has_visit = any(_num(_clean(r.get("n_visits")), int) or 0 > 1
                        for r in crows) or country in _VISIT_LEVEL_COUNTRIES
        text = render(country, crows, has_visit)
        if not args.check:
            (cdir / "recall.yml").write_text(text)
        written += 1

    verb = "would write" if args.check else "wrote"
    print(f"{verb} {written} recall.yml files from {len(rows)} rows; "
          f"no contradictions.")
    return 0


#: Countries whose delivered `food_acquired` carries a `visit` index level, so
#: the ask count is observable rather than merely claimed.  Kept explicit rather
#: than probed, so promotion needs no warm cache and no build.
_VISIT_LEVEL_COUNTRIES = {
    "GhanaLSS",
    # 2014 EMC carries `visit` 1..4 since the four-passage fix (#851);
    # its other waves get a constant `visit = 1` from add_visit_level,
    # which the `asks > 1` guard correctly leaves as `declared`.
    "Burkina_Faso",
}


if __name__ == "__main__":
    raise SystemExit(main())
