#!/usr/bin/env python
"""Promote the population survey from prose into config (GH #603 / #601).

Reads ``slurm_logs/POPULATION_STATEMENTS_2026-07-21.org`` -- a per-wave sweep of
all 111 wave directories the library shipped on 2026-07-21 -- and writes one
``lsms_library/countries/{C}/_/population.yml`` per country, keyed by **API wave
label** (the labels ``Country.waves`` yields, which are the values that appear in
the ``t`` index level).

Why a script rather than a hand transcription
---------------------------------------------
The record is 111 verbatim quotations of survey documentation in five languages,
with sic spellings the source doc goes out of its way to preserve.  A hand copy
would introduce exactly the silent corruption the sweep was written to avoid.
This script is the audit trail: re-run it and diff.  It follows the precedent of
``scripts/backfill_wave_provenance.py``.

What it checks before writing (any failure aborts)
--------------------------------------------------
1. Section 3 yields exactly 111 entries, each with all seven ``- Field ::``
   lines and the three mandatory ``#+begin_quote`` blocks.
2. Every entry's ``source_type`` / ``confidence`` / ``universe_tag`` agrees with
   the independent summary table in section 2.
3. The resulting tag / source_type / confidence histograms equal the counts the
   document itself publishes (37/28/18/11/7/5/2/1/1/1, 63/41/7, 84/25/2).
4. Every wave in ``Country.waves``, for every configured country, receives
   exactly one record -- and every doc row that receives none is reported.

Wave-label resolution
---------------------
The doc keys by wave *directory*.  Two countries' API wave labels differ:

* Nigeria is post-planting/post-harvest -- five wave directories, ten API wave
  labels (``2010Q3``/``2011Q1`` -> ``2010-11``, ...).  One doc row therefore
  expands to two config entries, each carrying ``documented_as: 2010-11``.
* Tanzania's four NPS rounds share the ``2008-15/`` directory, but its API wave
  labels (``2008-09``, ...) already match the doc's row labels, so no expansion
  is needed.

``wave_folder_map`` in the country module is the authority for both.

Rows whose wave has no live API label are still written, marked
``status: inert``, so the record survives even where the library cannot yet use
it (Afghanistan and Albania 1996 have no ``data_scheme.yml`` for that wave;
Benin ``2018-2019`` is a duplicate staging directory the doc itself says needs
no record).  Nothing from the sweep is discarded.

Usage
-----
    python scripts/promote_population_records.py            # write
    python scripts/promote_population_records.py --check    # verify only, no write
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
DOC = REPO / "slurm_logs" / "POPULATION_STATEMENTS_2026-07-21.org"

# The counts the source document publishes about itself (section 2, "Tag
# counts" and "Source and confidence counts").  Asserting against them turns a
# parser regression into a hard failure rather than a quiet under-count.
EXPECTED_TAGS = {
    "national-all-households": 37,
    "national-claimed": 28,
    "region-excluded": 18,
    "subnational-area": 11,
    "not-stated": 7,
    "panel-inherited": 5,
    "mixed-national+panel": 2,
    "rural-and-small-town": 1,
    "specialized": 1,
    "agricultural-households": 1,
}
EXPECTED_SOURCE_TYPES = {"local-documentation": 63, "wb-catalog": 41, "not-found": 7}
EXPECTED_CONFIDENCE = {"high": 84, "medium": 25, "low": 2}

FIELD_KEYS = {
    "Survey": "survey",
    "Source type": "source_type",
    "Confidence (as recorded by the extractor)": "confidence",
    "Universe tag (EDITORIAL, not a quote)": "universe_tag",
    "Language of the quoted source": "language",
    "Source file": "source_file",
    "Locator": "locator",
}
QUOTE_KEYS = {
    "Population statement, verbatim as recorded": "population_statement",
    "Exclusions, verbatim as recorded": "exclusions",
    "Extractor's notes (editorial prose about the evidence, not survey text)": "notes",
    "Translation (supplied by the extractor; NOT source text)": "translation",
}

HEADER = """\
# Population record -- what this survey's documentation says the sample
# represents.  One entry per wave, keyed by the API wave label (the value that
# appears in the `t` index level, i.e. an element of `Country(...).waves`).
#
# GENERATED by scripts/promote_population_records.py from
# slurm_logs/POPULATION_STATEMENTS_2026-07-21.org.  Edit the source document and
# re-run rather than editing this file by hand; every quoted block below is a
# verbatim transcription of survey documentation, sic spellings included.
#
#   THE TAG IS AN EDITORIAL READING.  IT IS NOT A QUOTE, AND NO DOCUMENT USES IT.
#
# `universe_tag` therefore never travels alone.  `source_type` says where the
# statement was found and `confidence` says how strongly it is a universe
# statement at all -- `medium` = "a coverage or representativeness claim, not a
# universe declaration"; `low` = "this is sample-design text and should not be
# laundered into a universe".  A reader who quotes the tag without those two has
# turned an editorial reading into a fact.
#
# `status: inert` marks a row the sweep recorded for a wave the library cannot
# currently build (no `_/data_scheme.yml`, or a duplicate staging directory).
# It is kept so the record is not lost, and is never returned by the loader.
"""


# ---------------------------------------------------------------------------
# parsing
# ---------------------------------------------------------------------------

def parse_summary_table(text: str) -> list[dict[str, str]]:
    """The independent (country, wave, source_type, confidence, tag) table."""
    m = re.search(r"#\+NAME: tbl:summary\n(.*?)\n\n", text, re.S)
    if m is None:
        raise SystemExit("summary table (#+NAME: tbl:summary) not found")
    rows = []
    for line in m.group(1).splitlines():
        if not line.startswith("|") or line.startswith("|-"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if cells[0] == "country":
            continue
        rows.append({
            "country": cells[0], "wave": cells[1],
            "source_type": cells[2], "confidence": cells[3],
            "universe_tag": cells[4],
        })
    return rows


def parse_entries(text: str) -> list[dict[str, Any]]:
    """Section 3, one dict per wave entry."""
    m = re.search(r"^\* 3\..*?(?=^\* 4\.)", text, re.S | re.M)
    if m is None:
        raise SystemExit("section 3 not found")
    sec3 = m.group(0)

    entries = []
    chunks = re.split(r"^\*\*\* ", sec3, flags=re.M)[1:]
    for chunk in chunks:
        heading, _, body = chunk.partition("\n")
        heading = heading.strip()
        country, _, wave = heading.rpartition(" ")
        rec: dict[str, Any] = {"country": country.strip(), "wave": wave.strip()}

        for label, key in FIELD_KEYS.items():
            mm = re.search(rf"^- {re.escape(label)} :: (.*)$", body, re.M)
            if mm is None:
                raise SystemExit(f"{heading}: missing field {label!r}")
            rec[key] = mm.group(1).strip()

        for label, key in QUOTE_KEYS.items():
            mm = re.search(
                rf"^{re.escape(label)}:\n\n#\+begin_quote\n(.*?)\n#\+end_quote",
                body, re.S | re.M,
            )
            rec[key] = mm.group(1).strip() if mm else None
        for label, key in QUOTE_KEYS.items():
            if key != "translation" and rec[key] is None:
                raise SystemExit(f"{heading}: missing quote block {label!r}")
        entries.append(rec)
    return entries


# ---------------------------------------------------------------------------
# wave-label resolution
# ---------------------------------------------------------------------------

def _load_country_module(cdir: Path):
    mod_path = cdir / "_" / f"{cdir.name.lower()}.py"
    if not mod_path.exists():
        return None
    try:
        spec = importlib.util.spec_from_file_location(f"_pop_{cdir.name}", mod_path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod
    except Exception:
        return None


def api_waves(cdir: Path) -> tuple[list[str], dict[str, str]]:
    """(API wave labels, wave_folder_map) for a country directory.

    Deliberately re-derives what ``Country.waves`` derives, instead of importing
    ``lsms_library`` -- this script must run against a config tree whose
    ``population.yml`` files do not exist yet, and must not depend on the
    library's own read path.
    """
    from lsms_library.yaml_utils import load_yaml

    mod = _load_country_module(cdir)
    folder_map: dict[str, str] = {}
    if mod is not None and hasattr(mod, "wave_folder_map"):
        folder_map = dict(mod.wave_folder_map)
    if mod is not None and hasattr(mod, "waves"):
        return sorted(mod.waves), folder_map
    if mod is not None and hasattr(mod, "Waves"):
        return sorted(mod.Waves.keys()), folder_map

    scheme = cdir / "_" / "data_scheme.yml"
    if scheme.exists():
        res = load_yaml(scheme) or {}
        if res.get("Waves"):
            return sorted(res["Waves"]), dict(res.get("wave_folder_map") or {})
        found = sorted(
            p.name for p in cdir.iterdir()
            if p.is_dir()
            and ((p / "Documentation" / "SOURCE.org").exists()
                 or (p / "Documentation" / "SOURCE").exists())
        )
        return found, folder_map
    return [], folder_map


# ---------------------------------------------------------------------------
# emitting
# ---------------------------------------------------------------------------

def _block(value: str, indent: str) -> str:
    """A YAML literal block scalar, so no quoting can mangle the verbatim text.

    ``|-`` (strip) keeps the value byte-identical to the doc's quote body.  Any
    line that would be ambiguous is still safe here: inside a block scalar
    nothing is escaped and nothing is interpreted.
    """
    lines = value.split("\n")
    out = ["|-"]
    for line in lines:
        out.append(f"{indent}{line}" if line else "")
    return "\n".join(out)


def render(country: str, records: list[dict[str, Any]]) -> str:
    parts = [HEADER, "\nPopulation:\n"]
    for rec in records:
        parts.append(f"  {_yaml_key(rec['wave'])}:\n")
        for key in ("universe_tag", "source_type", "confidence"):
            parts.append(f"    {key}: {rec[key]}\n")
        if rec.get("status"):
            parts.append(f"    status: {rec['status']}\n")
        if rec.get("status_reason"):
            parts.append(f"    status_reason: {_scalar(rec['status_reason'])}\n")
        if rec.get("documented_as"):
            parts.append(f"    documented_as: {_yaml_key(rec['documented_as'])}\n")
        for key in ("survey", "language", "source_file", "locator"):
            parts.append(f"    {key}: {_scalar(rec[key])}\n")
        for key in ("population_statement", "exclusions", "translation", "notes"):
            val = rec.get(key)
            if not val:
                continue
            parts.append(f"    {key}: {_block(val, '      ')}\n")
        parts.append(
            "    record_source: "
            "slurm_logs/POPULATION_STATEMENTS_2026-07-21.org"
            f" (section 3, '{country} {rec['documented_as'] or rec['wave']}')\n"
        )
    return "".join(parts)


def _yaml_key(value: str) -> str:
    """Quote a wave label so YAML never reads it as a number or a date.

    ``2020`` would parse as ``int`` and ``2018-19`` is fine, but ``1996`` and
    ``2007`` are ints too -- and the loader compares against string wave labels.
    Always quote.
    """
    return "'" + value.replace("'", "''") + "'"


def _scalar(value: str) -> str:
    return "'" + str(value).replace("'", "''") + "'"


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def build(countries_dir: Path) -> tuple[dict[str, list[dict]], list[str]]:
    text = DOC.read_text(encoding="utf-8")
    table = parse_summary_table(text)
    entries = parse_entries(text)

    if len(entries) != 111:
        raise SystemExit(f"expected 111 entries in section 3, parsed {len(entries)}")
    if len(table) != 111:
        raise SystemExit(f"expected 111 summary rows, parsed {len(table)}")

    by_key = {(e["country"], e["wave"]): e for e in entries}
    for row in table:
        key = (row["country"], row["wave"])
        entry = by_key.get(key)
        if entry is None:
            raise SystemExit(f"summary row {key} has no section-3 entry")
        for field in ("source_type", "confidence", "universe_tag"):
            if entry[field] != row[field]:
                raise SystemExit(
                    f"{key}: section 3 says {field}={entry[field]!r} but the "
                    f"summary table says {row[field]!r}"
                )

    for name, got, want in (
        ("universe_tag", Counter(e["universe_tag"] for e in entries), EXPECTED_TAGS),
        ("source_type", Counter(e["source_type"] for e in entries), EXPECTED_SOURCE_TYPES),
        ("confidence", Counter(e["confidence"] for e in entries), EXPECTED_CONFIDENCE),
    ):
        if dict(got) != want:
            raise SystemExit(f"{name} histogram {dict(got)} != published {want}")

    # ---- resolve doc wave labels to API wave labels -----------------------
    per_country: dict[str, list[dict]] = defaultdict(list)
    unplaced: list[str] = []
    doc_countries = sorted({e["country"] for e in entries})
    for country in doc_countries:
        cdir = countries_dir / country
        if not cdir.is_dir():
            for e in (x for x in entries if x["country"] == country):
                unplaced.append(f"{country} {e['wave']} (no country directory)")
            continue
        waves, folder_map = api_waves(cdir)
        wave_set = set(waves)
        # directory -> [api labels]  (Nigeria: '2010-11' -> [2010Q3, 2011Q1])
        dir_to_api: dict[str, list[str]] = defaultdict(list)
        for api_label, folder in folder_map.items():
            if api_label in wave_set:
                dir_to_api[folder].append(api_label)

        for e in sorted((x for x in entries if x["country"] == country),
                        key=lambda r: r["wave"]):
            if e["wave"] in wave_set:
                targets = [(e["wave"], None)]
            elif e["wave"] in dir_to_api:
                targets = [(a, e["wave"]) for a in sorted(dir_to_api[e["wave"]])]
            else:
                targets = [(e["wave"], None)]
            for api_label, documented_as in targets:
                rec = dict(e)
                rec["wave"] = api_label
                rec["documented_as"] = documented_as
                if api_label in wave_set:
                    rec["status"] = None
                    rec["status_reason"] = None
                else:
                    rec["status"] = "inert"
                    rec["status_reason"] = (
                        "recorded by the 2026-07-21 sweep; no such wave in "
                        "Country.waves (the wave is not configured, or the "
                        "directory is a duplicate staging area)"
                    )
                per_country[country].append(rec)

    for country in per_country:
        per_country[country].sort(key=lambda r: r["wave"])
    return dict(per_country), unplaced


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="parse + validate, report, but write nothing")
    ap.add_argument("--countries-dir", default=None,
                    help="config tree root (default: the in-repo one)")
    args = ap.parse_args(argv)

    sys.path.insert(0, str(REPO))
    countries_dir = (Path(args.countries_dir) if args.countries_dir
                     else REPO / "lsms_library" / "countries")

    per_country, unplaced = build(countries_dir)

    n_active = sum(1 for recs in per_country.values()
                   for r in recs if r["status"] is None)
    n_inert = sum(1 for recs in per_country.values()
                  for r in recs if r["status"] == "inert")
    print(f"{len(per_country)} countries, {n_active} active records, "
          f"{n_inert} inert records")
    for recs in per_country.values():
        for r in recs:
            if r["status"] == "inert":
                print(f"  inert: {r['country']} {r['wave']}")
    for u in unplaced:
        print(f"  UNPLACED: {u}")

    # every configured wave must be covered
    missing = []
    for cdir in sorted(p for p in countries_dir.iterdir() if p.is_dir()):
        waves, _ = api_waves(cdir)
        if not (cdir / "_" / "data_scheme.yml").exists():
            continue
        have = {r["wave"] for r in per_country.get(cdir.name, [])}
        for w in waves:
            if w not in have:
                missing.append(f"{cdir.name} {w}")
    if missing:
        print(f"  UNCOVERED API WAVES ({len(missing)}): {missing}")
    else:
        print("  every API wave of every configured country has a record")

    if args.check:
        return 1 if (missing or unplaced) else 0

    for country, recs in sorted(per_country.items()):
        out = countries_dir / country / "_" / "population.yml"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(render(country, recs), encoding="utf-8")
        print(f"  wrote {out.relative_to(countries_dir.parent.parent)} "
              f"({len(recs)} records)")
    return 1 if (missing or unplaced) else 0


if __name__ == "__main__":
    raise SystemExit(main())
